name: Hub Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Vercel Deploy
        run: |
          npm i -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
      - name: Cloudflare Pages (optional)
        if: ${{ secrets.CF_API_TOKEN != '' }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT }}/pages/projects/${{ secrets.CF_PROJECT }}/deployments" \
               -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}"
      - name: Replicate warmup (optional)
        if: ${{ secrets.REPLICATE_API_TOKEN != '' }}
        run: |
          curl -X POST https://api.replicate.com/v1/predictions \
            -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"version":"<model_version>","input":{"prompt":"warmup"}}'
